### ISSUE TITLE
Away version

### ISSUE THREAD

**Issue by JohnBrookes** [away3d/awayphysics-core-fp11#13]
Any chance of adding an Away version check to the physics.
maybe in AWPDynamicsWorld.getinstance
DEV branch

if (Away3D.MAJOR_VERSION ==4 && Away3D.MINOR_VERSION < 1)
            throw new Error("Incorrect AWAY3D version "+Away3D.MAJOR_VERSION+"."+Away3D.MINOR_VERSION+ ". Use Away3D 4.1 or higher");

**Comment by muzerly** [comment]
Could you pull a request of this function ? There is no development environment on my side currently.

ÔÚ 2013-5-14£¬ÏÂÎç8:02£¬JohnBrookes notifications@github.com Ð´µÀ£º

**Comment by samehhelaly** [comment]
Hi man
i have download the core and put awaya3d and com folders inside the src folder to be with away3dphysics folder then i make as3proj by flashdevelop and try to run the examples but it give me error that he did not found cmodule.awayphysics in AWPBase.as line 2 
please tell me what to do or what is missing
