### ISSUE TITLE
BVH and subgeoms

### ISSUE THREAD

**Issue by JohnBrookes** [away3d/awayphysics-core-fp11#21]
Needed both types of subg to work with bvh.

**Comment by muzerly** [comment]
I haven't look the away3d code for a long time, it's support multiple types of subgeoms now?

**Comment by JohnBrookes** [comment]
BVH only works with the first subgeometry and expects compactSubGeomtery.

Away has CompactSubgeometry and SubGeometry.
The default for primitives/models is compactSubgeomtry. Elevation uses Subgeomtery

CompactSubgeometry has vertices,normals,tangents,uv,uv2 in the vertexData Vector.
Subgeometry has  only vertices in the vertexData Vector.

To see issue
BvhTriangleMeshCarTest.as #103
https://github.com/away3d/awayphysics-examples-fp11/blob/master/src/BvhTriangleMeshCarTest.as#L103

sceneMesh.geometry.convertToSeparateBuffers(); \converts compact to SubG

**Comment by JohnBrookes** [comment]
Just noticed issue with more than 1 subgeomtetry.. forgot index data.. 
Will redo.
