### ISSUE TITLE
Hinge and compound shape

### ISSUE THREAD

**Issue by JohnBrookes** [away3d/awayphysics-core-fp11#4]
If you create a compound shape and add a box shape to that compound shape.
If the box shape doesn't touch the center of the compound shape it stops a hinge from rotating.
Easier to show than expain.
http://www.shrewballooba.co.uk/ConstraintTest2.as

try either
modelCompound.addChildShape(modelPart1Shape, new Vector3D(0, 0, -900), new Matrix3D()); //rotates
//modelCompound.addChildShape(modelPart1Shape, new Vector3D(0, 0, -1000), new Matrix3D());  //sticks

**Comment by JohnBrookes** [comment]
OK, so whats happening is the rigidbody is falling asleep.
modelRigidBody.activationState = AWPCollisionObject.DISABLE_DEACTIVATION;
stops the above happening. Weird that you only need it for certain case.

**Comment by muzerly** [comment]
Yes, you can also increase the third parameter in setAngularMotor. Like: Hinge.setAngularMotor(true,500,200);
